# This workflow was stared from the default GitHub workflow for .NET Core WP
# desktop apps. See more details here https://github.com/microsoft/github-actions-for-desktop-apps

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-and-test:

    strategy:
      matrix:
        configuration: [Debug]    # Later add Release when needed

    runs-on: windows-2022    # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100-rc.2.21505.57
        include-prerelease: true

    - name: Build
      run: msbuild StandardUI.sln /restore /p:Configuration=Release
      